//-----APP
export const API_URL = 'http://localhost:3000/api/v1/'
export const APP_URL = 'http://localhost:3001/'


export const ADD_AUCTION = 'ADD_AUCTION';
export const FETCH_AUCTIONS = 'FETCH_AUCTIONS';
export const FETCH_AUCTIONS_LOADING = 'FETCH_AUCTIONS_LOADING';
export const FETCH_AUCTION_COMPLETE = 'FETCH_AUCTION_COMPLETE';
export const GET_CURRENT_AUCTION = 'GET_CURRENT_AUCTION';
export const FETCH_CURRENT_AUCTION_BIDS = "FETCH_CURRENT_AUCTION_BIDS";
export const FETCH_CURRENT_AUCTION_BIDS_LOADING = "FETCH_CURRENT_AUCTION_BIDS_LOADING";
export const FETCH_CURRENT_AUCTION_BIDS_COMPLETE = "FETCH_CURRENT_AUCTION_BIDS_COMPLETE";
export const CURRENT_AUCTION_SELLER = 'CURRENT_AUCTION_SELLER'

export const PLACE_BID = 'PLACE_BID'

//--------USER CONSTANTS
export const CREATING_USER = "CREATING_USER";
export const LOGGING_IN = "LOGGING_IN";
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const CURRENT_USER = 'CURRENT_USER';




